// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendnet.Data;

#nullable disable

namespace backendnet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.Property<int>("CategoriesCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesCategoryId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("CategoryMovie");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Protected")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Acción",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Aventura",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Animación",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Ciencia ficción",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Comedia",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Crimen",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Documental",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Drama",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Familiar",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Fantasia",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Historia",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Horror",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Musica",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Misterio",
                            Protected = true
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Romance",
                            Protected = true
                        });
                });

            modelBuilder.Entity("backend.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Poster = "N/A",
                            Synopsis = "El banquero Andy Dufresne es arrestado por matar a su esposa",
                            Title = "Sueño de fuga",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 2,
                            Poster = "N/A",
                            Synopsis = "El patriarca de una organización criminal transfiere el cont",
                            Title = "El padrino",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 3,
                            Poster = "N/A",
                            Synopsis = "Cuando el Joker emerge causando caos y violencia en",
                            Title = "El caballero oscuro",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 4,
                            Poster = "N/A",
                            Synopsis = "Gandalf y Aragorn lideran el mundo de los hombres, e",
                            Title = "El retorno del rey",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 5,
                            Poster = "N/A",
                            Synopsis = "Las vidas de dos mafiosos, un boxeador, la esposa de",
                            Title = "Tiempos violentos",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 6,
                            Poster = "N/A",
                            Synopsis = "Las presidencias de Kennedy y Johnson, los eventos de Viet",
                            Title = "Forrest Gump",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 7,
                            Poster = "N/A",
                            Synopsis = "Un hombre deprimido conoce a un fabricante de jabon",
                            Title = "El club de la pelea",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 8,
                            Poster = "N/A",
                            Synopsis = "A un ladrón que roba secretos corporativos a través de la tec",
                            Title = "Inception",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 9,
                            Poster = "N/A",
                            Synopsis = "Los rebeldes han vencido",
                            Title = "Star Wars: Episodio V - El imperio contraataca",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 10,
                            Poster = "N/A",
                            Synopsis = "Un hacker se da cuenta por medio de otros rebeldes de la natura",
                            Title = "Matrix",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 11,
                            Poster = "N/A",
                            Synopsis = "Un grupo de exploradores prueban los saltos a través de a",
                            Title = "Interestelar",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 12,
                            Poster = "N/A",
                            Synopsis = "Paul Atreides se une a Chani y los Fremen mientras bus",
                            Title = "Dune: Parte dos",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 13,
                            Poster = "N/A",
                            Synopsis = "Un cyborg, idéntico al que fracasó al as",
                            Title = "Terminator 2: El juicio final",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 14,
                            Poster = "N/A",
                            Synopsis = "Marty McFly, un estudiante de 17 años, es enviado acc",
                            Title = "Volver al futuro",
                            Year = 0
                        },
                        new
                        {
                            MovieId = 15,
                            Poster = "N/A",
                            Synopsis = "Vivir en Barbie Land es ser un ser perfecto en un lugar perfect",
                            Title = "Barbie",
                            Year = 0
                        });
                });

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.HasOne("backend.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
